# -*- coding: utf-8 -*-
"""main_spike_latest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJIebxvh-BN8hIYgq2lHMIhfIH1YbhFM

# 準備/Setup

### ライブラリのインポート/Import libraries
"""

# 必要なライブラリのインポート
import torch
import numpy as np
import os
from datetime import datetime
from tqdm import tqdm
import argparse
import matplotlib.pyplot as plt
from PIL import Image
import glob
import cv2
import matplotlib.animation as animation
from skimage.metrics import structural_similarity as ssim

"""### 引数の設定/Setting arguments"""

num_delta = 100    # Number of delta points

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
seed_psf = 41   # Random seed for PSF
seed_gaussian_noise = 41    # Random seed for Gaussian noise
seed_L_hat = 42   # Random seed for L_hat initialization
img_height = 60   # Input image height
img_width = 80    # Input image width
num_frames = 100   # Number of temporal frames
dataset_name = "/home/arima/work/data/video2"    # Dataset path
first_frame_num = 0    # Starting frame number
radiance_threshold = 1.0    # radiance threshold
snr_db = 30.0   # AWGN SNR [dB] added after PSF convolution (inf for none)

# Optimization Parameters
margin = 0.0    # Margin for spike loss
lambda_tv = 0.10345001220703126   # Weight for 3D TV loss
x_weight = 1.0    # 3D TV x-direction weight
y_weight = 1.0    # 3D TV y-direction weight
t_weight = 1.0    # 3D TV t-direction weight
learning_rate = 0.066741943359375   # Learning rate
num_iterations = 1000   # Number of gradient descent iterations

"""### データセット読み込み/Load dataset"""

def load_dataset(dataset_name, img_height, img_width, first_frame_num, num_frames, device):
    """
    Loads images from the DAVIS 2017 dataset format or similar structures.
    Converts RGB frames to grayscale and normalizes the tensor.
    """
    print(f"Generating Ground Truth images for sequence: {dataset_name}...")

    # Path adjusted for DAVIS 2017 structure: JPEGImages/Resolution/Sequence
    image_dir = os.path.join(dataset_name)

    if not os.path.exists(image_dir):
        raise FileNotFoundError(f"Directory not found: {image_dir}")

    image_paths = sorted(
        [os.path.join(image_dir, f) for f in os.listdir(image_dir)
         if f.lower().endswith((".png", ".jpg", ".jpeg"))]
    )
    print(len(image_paths))
    image_paths = image_paths[first_frame_num : first_frame_num + num_frames]

    if len(image_paths) == 0:
        raise ValueError("No images found in the specified range.")

    L_gt_list = []
    for path in image_paths:
        # DAVIS images are RGB; .convert("L") applies the ITU-R 601-2 luma transform:
        # L = R * 299/1000 + G * 587/1000 + B * 114/1000
        img_pil = Image.open(path).convert("L")
        img_resized = img_pil.resize((img_width, img_height), resample=Image.BILINEAR)
        img_np = np.array(img_resized).astype(np.float32)
        L_gt_list.append(torch.from_numpy(img_np))

    L_gt = torch.stack(L_gt_list) # Shape: (T, H, W)

    # Global normalization to [0, 1] range
    min_val = L_gt.min()
    max_val = L_gt.max()
    L_gt = (L_gt - min_val) / (max_val - min_val)

    #print(L_gt.shape)

    return L_gt.to(device)

"""# PSFエンジニアリング/PSF engineering

### 点拡がり関数（PSF）の作成/Create PSF
"""

def create_psf(img_height, img_width, num_delta, seed, device):
    """Generates the Point Spread Function (PSF)."""
    gen_psf = torch.Generator().manual_seed(seed)
    h_psf = torch.zeros(img_height, img_width)

    if num_delta == 1:
        # Identity mapping (center pixel)
        center_y = img_height // 2
        center_x = img_width // 2
        h_psf[center_y, center_x] = 1.0
    else:
        # Random k-points
        # 画像の全座標を生成
        coords = torch.cartesian_prod(torch.arange(img_height), torch.arange(img_width))
        # ランダムにnum_delta個の座標を選択
        selected_indices = coords[torch.randperm(len(coords), generator=gen_psf)[:num_delta]]
        # 選択された座標に1.0を配置
        for y, x in selected_indices:
            h_psf[y, x] = 1.0

    h_psf = h_psf.to(device)
    h_psf /= h_psf.sum() # Normalize
    return h_psf

"""### 撮影動画とPSFの畳み込み/Convolve sequence with PSF

$g = L * h$
"""

def convolve_sequence_with_psf(L_seq, psf):
    """
    Convolves the entire video sequence with the PSF using FFT.
    L_seq: (T, H, W) Tensor
    psf: (H, W) Kernel
    """
    T, H, W = L_seq.shape

    # Broadcast PSF to (T, H, W)
    # PSFは空間的に同じなので、FFTで一度計算すれば全フレームに適用できる
    h_shifted = torch.fft.fftshift(psf)
    H_fft = torch.fft.fft2(h_shifted, s=(H, W))

    # L_seqの各フレームに対してFFTを計算
    F_L = torch.fft.fft2(L_seq)        # (T, H, W)
    # PSFのFFTを全フレームに適用するためにブロードキャスト
    F_H = H_fft[None, :, :]            # Broadcast to (1, H, W)
    F_conv = F_L * F_H

    # 逆FFTで空間領域に戻す
    conv_result = torch.fft.ifft2(F_conv).real
    return conv_result

"""# 観測ノイズの付加/Add noise"""

def add_awgn(x, snr_db, seed=None):
    """Adds Additive White Gaussian Noise based on SNR."""
    if not np.isfinite(snr_db):
        return x

    sig_power = (x.float().pow(2).mean()).item()
    if sig_power <= 0:
        return x

    sig_power_db = 10.0 * np.log10(sig_power)
    noise_power_db = sig_power_db - snr_db
    noise_power = 10.0 ** (noise_power_db / 10.0)

    gen = torch.Generator().manual_seed(seed) if seed else None
    noise = torch.randn(x.shape, generator=gen) * np.sqrt(noise_power)
    noise = noise.to(x.device)

    return x + noise

"""# スパイクを計測/Detecting spikes"""

def generate_accum_map(g_seq, threshold):
    num_frames, height, width = g_seq.shape
    device = g_seq.device

    # 参照フレームの初期化
    g_ref_seq = torch.zeros_like(g_seq).to(device)
    g_ref_seq[0] = g_seq[0]
    g_ref = g_ref_seq[0].clone()

    accum_map = torch.zeros_like(g_seq).to(device)
    accum_map[0] = g_seq[0]
    accum_ref = g_seq[0].clone()

    for t in range(1, num_frames):
        current_accum_value = accum_ref + g_seq[t]
        accum_map[t] = current_accum_value.clone()

        # しきい値に基づいてスパイクの有無を決定
        s = torch.zeros_like(current_accum_value).to(device)
        s[current_accum_value >= threshold]  =  1.0

        accum_ref = current_accum_value.clone()
        accum_ref = torch.where(s == 1.0, accum_ref - threshold, accum_ref)

        # Update reference intensity: g_ref <- g_ref + theta * s
        g_ref = g_ref + threshold * s
        g_ref_seq[t] = g_ref

    return accum_map, g_ref_seq

def generate_events(accum_map, threshold):
    """Generates discrete event map (+1, 0, -1) from delta map."""
    device = accum_map.device
    sigma = torch.zeros_like(accum_map).to(device)
    sigma[accum_map >= threshold] = 1.0
    photon_sum = torch.sum(sigma, dim=0) * threshold
    return sigma, photon_sum

def accum_spike(sigma_gt, gt):
    spike_accum = torch.cumsum(sigma_gt, dim=0)
    photon_accum = torch.cumsum(gt, dim=0)

    return spike_accum, photon_accum

"""# TFW・TFI

### TFW
"""

def tfw(sigma_gt, w):
    spike_cumsum = torch.cumsum(sigma_gt, dim=0)

    tfw_sum = torch.zeros_like(sigma_gt)

    tfw_sum[w-1:] = spike_cumsum[w-1:]
    tfw_sum[w:] -= spike_cumsum[:-w]

    tfw_img = (tfw_sum / w) * radiance_threshold
    tfw_img = torch.clamp(tfw_img, max=1.0)
    return tfw_img

"""### TFI"""

def tfi(sigma_gt, radiance_threshold):
  tfi_img_ref = torch.zeros_like(sigma_gt).to(device)
  tfi_img_ref[0] = torch.ones_like(sigma_gt[0])
  for i in range(1, len(sigma_gt)):
    tfi_img_ref[i] = torch.where(sigma_gt[i - 1] == 1, 1, tfi_img_ref[i - 1] + 1)
  #print(tfi_img_ref)
  tfi_img = torch.zeros_like(sigma_gt).to(device)
  tfi_img[-1] = tfi_img_ref[-1]
  for j in range(len(sigma_gt) - 1, 0, -1):
    #print(j)
    tfi_img[j - 1] = torch.where(tfi_img_ref[j - 1] < tfi_img_ref[j], tfi_img[j], tfi_img_ref[j - 1])
  #print(tfi_img)
  tfi_img = 1 / tfi_img
  tfi_img = tfi_img * radiance_threshold
  tfi_img = torch.clamp(tfi_img, max=1.0)
  return tfi_img

"""# 損失関数/Loss Function"""

def hinge_loss_ver2(gt, sigma_gt, threshold, epsilon):
    """Calculates the Hinge-like event loss."""
    spike_accum, photon_accum = accum_spike(sigma_gt, gt)
    photon_sup = (spike_accum + 1) * threshold
    photon_inf = spike_accum * threshold

    over_loss = torch.clamp(photon_accum - photon_sup, min=0.0).sum()
    under_loss = torch.clamp(photon_inf - photon_accum, min=0.0).sum()

    return over_loss + under_loss

# 正則化項として、隣接ピクセル・フレーム間の滑らかさに関する条件を入れる
def total_variation_3d(x, x_weight, y_weight, t_weight, reduction='sum'):
    """Calculates Spatio-Temporal Total Variation."""
    if x.dim() != 3:
        raise ValueError("Input must be 3D tensor")

    T, H, W = x.shape
    eps = 1e-8

    # 時間、空間の差分を計算（最後のフレーム/行/列は0でパディング）
    dt = torch.cat([x[1:] - x[:-1], torch.zeros(1,H,W, device=x.device, dtype=x.dtype)], dim=0)
    dy = torch.cat([x[:,1:] - x[:,:-1], torch.zeros(T,1,W, device=x.device, dtype=x.dtype)], dim=1)
    dx = torch.cat([x[:,:,1:] - x[:,:,:-1], torch.zeros(T,H,1, device=x.device, dtype=x.dtype)], dim=2)
    tv = torch.sqrt(eps + t_weight*dt**2 + y_weight*dy**2 + x_weight*dx**2)
    return tv.sum()

"""# 最適化処理/Optimization

with PSF engineering, Hinge Loss ver2
"""

def run_optimization_ver2(seed_L_hat, num_frames, img_height, img_width, learning_rate, num_iterations, x_weight, y_weight, t_weight, lambda_tv, L_gt, h_psf, radiance_threshold, sigma_gt, photon_sum, margin):
    """Main Optimization Loop."""

    # 1. Initialize L_hat
    print("Initializing reconstruction...")
    gen_L_hat = torch.Generator().manual_seed(seed_L_hat)


    L_hat = torch.rand(num_frames, img_height, img_width, generator=gen_L_hat)
    L_hat /= L_hat.mean()
    L_hat = L_hat.to(device).detach().clone().requires_grad_(True)

    optimizer = torch.optim.AdamW([L_hat], lr=learning_rate)

    # 2. Loop
    print(f"Starting Adam optimization ({num_iterations} iterations)...")
    loss_history = []
    loss_spike_history = []
    loss_tv_history = []

    best_loss = float('inf')
    best_L_hat = None

    for iteration in tqdm(range(1, num_iterations + 1)):
        optimizer.zero_grad()

        # Forward
        g_hat = convolve_sequence_with_psf(L_hat, h_psf)

        # Loss
        l_event = hinge_loss_ver2(g_hat, sigma_gt, radiance_threshold, margin)
        l_tv = total_variation_3d(L_hat, x_weight, y_weight, t_weight, reduction='sum')
        loss = l_event + lambda_tv * l_tv

        loss.backward()
        optimizer.step()

        # Projection / Constraints
        with torch.no_grad():
            #L_hat.div_(L_hat.mean())
            L_hat.clamp_(min=0.0, max=1.0)
            #L_hat.div_(torch.sum(L_hat, dim=0) / photon_sum)

        # Logging
        loss_val = loss.item()
        loss_history.append(loss_val)
        loss_spike_history.append(l_event.item())
        loss_tv_history.append(l_tv.item())

        if loss_val < best_loss:
            best_loss = loss_val
            best_L_hat = L_hat.detach().clone()

        if iteration % (num_iterations // 10) == 0:
            tqdm.write(f"Iter {iteration}: Loss={loss_val:.6f} (Ev={l_event.item():.6f}, TV={l_tv.item():.6f})")

    print("Optimization Complete.")
    return best_L_hat, loss_history, loss_spike_history, loss_tv_history, best_loss

"""# 評価指標 / Evaluation

## PSNRの計算/Calculation of PSNR
"""

def psnr(gt, pred):
    mse = torch.mean((gt - pred) ** 2)
    if mse == 0:
        return float('inf')
    max_pixel = 1.0
    return 20 * torch.log10(max_pixel / torch.sqrt(mse))

"""## SSIMの計算/Calculation of SSIM"""

def ssim_video(gt, pred, data_range=1.0):
    gt_np = gt.detach().cpu().numpy()
    pred_np = pred.detach().cpu().numpy()

    ssim_list = []
    for t in range(gt_np.shape[0]):
        score = ssim(
            gt_np[t],
            pred_np[t],
            data_range=data_range
        )
        ssim_list.append(score)

    return np.mean(ssim_list)

"""# 閾値の設定"""

from math import inf
def set_threshold(g_gt, device):
  spike_gt_list = [100000, 80000, 60000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000]
  threshold_list = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  spike_count_list = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  j = 0
  delta = [float('inf')] * 11
  for i in range(10000):
    radiance_threshold = i * 0.01
    accum_gt_g, _ = generate_accum_map(g_gt, radiance_threshold)
    sigma_gt_g, _ = generate_events(accum_gt_g, radiance_threshold)
    count = torch.count_nonzero(sigma_gt_g).item()
    if delta[j] >= abs(spike_gt_list[j] - count):
      delta[j] = abs(spike_gt_list[j] - count)
      threshold_list[j] = radiance_threshold
      spike_count_list[j] = count
    else:
      j += 1
      if j == 11:
        break
  for k in range(11):
    print(f"Total GT Spikes: {spike_count_list[k]}")
    print(f"Threshold: {round(threshold_list[k], 2)}")
  return threshold_list, spike_count_list

"""# パラメータ調整/Tuning parameters"""

def objective_function(x, sigma_gt_g, photon_sum_g):
    best_L_hat_wo_PSF_ver2, loss_history, loss_sp, loss_tv, best_loss = run_optimization_ver2(seed_L_hat, num_frames, img_height, img_width, x[0], num_iterations, x_weight, y_weight, x[2], x[1], L_gt, h_psf, radiance_threshold, sigma_gt_g, photon_sum_g, margin)
    return -psnr(L_gt, best_L_hat_wo_PSF_ver2), ssim_video(L_gt, best_L_hat_wo_PSF_ver2)

def hooke_jeeves_opt(f, x0, alpha, epsilon, gamma=0.5):
    x = np.array(x0, dtype=float)
    y, _ = f(x, sigma_gt_g, photon_sum_g)
    n = len(x)
    iter = 1

    while alpha > epsilon and iter <= 12:
        improved = False
        x_best, y_best = x.copy(), y

        for i in range(n):
            for sgn in [-1, 1]:
                x_phi = x.copy()

                x_phi[i] += sgn * alpha * x[i]

                y_phi, z_phi = f(x_phi, sigma_gt_g, photon_sum_g)

                if y_phi < y_best:
                    x_best, y_best, z_best = x_phi, y_phi, z_phi
                    improved = True

        x, y, z = x_best, y_best, z_best
        if not improved:
            alpha *= gamma
            print(f"Step size reduced: alpha={alpha}")
            print(f"Current PSNR={-y}")

        if improved:
            print(f"Current learning rate={x[0]}")
            print(f"Current lambda tv={x[1]}")
            print(f"Current t_weight={x[2]}")
            print(f"Current PSNR={-y}")
        iter += 1
    return x

"""# メイン処理 / Main"""

L_gt = load_dataset(dataset_name, img_height, img_width, first_frame_num, num_frames, device)
print("観測対象")
plt.imshow(L_gt.to('cpu').detach()[15], cmap='Greys')
plt.show()
h_psf = create_psf(img_height, img_width, num_delta, seed_psf, device)
g_gt = convolve_sequence_with_psf(L_gt, h_psf)
g_gt = add_awgn(g_gt, snr_db, seed=seed_gaussian_noise)
g_gt = torch.clamp(g_gt, min=0.0) # Handle numerical negs
print("入力光")
plt.imshow(g_gt.to('cpu').detach()[15], cmap='Greys')
plt.show()

# 閾値の設定
threshold_list, spike_count_list = set_threshold(g_gt, device)

if num_delta == 1:
  psnr_tfw_list = [0.0] * 11
  psnr_tfi_list = [0.0] * 11
  ssim_tfw_list = [0.0] * 11
  ssim_tfi_list = [0.0] * 11
  result_tfw_list = []
  result_tfi_list = []
psnr_gd_list = [0.0] * 11
ssim_gd_list = [0.0] * 11
result_gd_list = []
spike_list = []

for loop in range(11):
  radiance_threshold = round(threshold_list[loop], 2)
  accum_gt_g, g_ref_seq = generate_accum_map(g_gt, radiance_threshold)
  sigma_gt_g, photon_sum_g = generate_events(accum_gt_g, radiance_threshold)
  print("観測結果")
  print(f"Total GT Spikes: {spike_count_list[loop]}")
  plt.imshow(sigma_gt_g.to('cpu').detach()[15], cmap='Greys')
  plt.show()
  spike_list.append(sigma_gt_g.clone())

  initial_params = [0.01, 0.01, 1.0]

  best_params = hooke_jeeves_opt(
      objective_function,
      initial_params,
      alpha=0.5,
      epsilon=0.01
  )

  print(f"Optimal LR: {best_params[0]}, Optimal TV: {best_params[1]}, Optimal t_weight: {best_params[2]}")
  lambda_tv = best_params[1]   # Weight for 3D TV loss
  t_weight = best_params[2]    # 3D TV t-direction weight
  learning_rate = best_params[0]   # Learning rate

  if num_delta == 1:
    tfw_img = tfw(sigma_gt_g, 10)
    print(f"TFW reconstruction")
    plt.imshow(tfw_img.to('cpu').detach()[15], cmap='Greys')
    plt.show()
    tfi_img = tfi(sigma_gt_g, radiance_threshold)
    print("TFI reconstruction")
    plt.imshow(tfi_img.to('cpu').detach()[15], cmap='Greys')
    plt.show()

  best_L_hat_ver2, loss_history, loss_sp, loss_tv, best_loss = run_optimization_ver2(seed_L_hat, num_frames, img_height, img_width, learning_rate, num_iterations, x_weight, y_weight, t_weight, lambda_tv, L_gt, h_psf, radiance_threshold, sigma_gt_g, photon_sum_g, margin)
  print("gradient descent reconstruction")
  plt.imshow(best_L_hat_ver2.to('cpu').detach()[15], cmap='Greys')
  plt.show()

  print(f"Total GT Spikes: {spike_count_list[loop]}")
  print(f"Threshold: {radiance_threshold}")
  if num_delta == 1:
    result_tfw_list.append(tfw_img.clone())
    result_tfi_list.append(tfi_img.clone())
    psnr_tfw = psnr(L_gt, tfw_img)
    print(f"PSNR of TFW: {psnr_tfw}")
    ssim_tfw = ssim_video(L_gt, tfw_img)
    print(f"SSIM of TFW: {ssim_tfw}")
    psnr_tfi = psnr(L_gt, tfi_img)
    print(f"PSNR of TFI: {psnr_tfi}")
    ssim_tfi = ssim_video(L_gt, tfi_img)
    print(f"SSIM of TFI: {ssim_tfi}")
    psnr_tfw_list[loop] = np.round(psnr_tfw.to('cpu').detach().numpy().copy(), 2)
    ssim_tfw_list[loop] = round(ssim_tfw, 4)
    psnr_tfi_list[loop] = np.round(psnr_tfi.to('cpu').detach().numpy().copy(), 2)
    ssim_tfi_list[loop] = round(ssim_tfi, 4)

  result_gd_list.append(best_L_hat_ver2.clone())
  psnr_with_PSF_ver2 = psnr(L_gt, best_L_hat_ver2)
  print(f"PSNR of gradient descent: {psnr_with_PSF_ver2}")
  ssim_with_PSF_ver2 = ssim_video(L_gt, best_L_hat_ver2)
  print(f"SSIM of gradient descent: {ssim_with_PSF_ver2}")
  psnr_gd_list[loop] = np.round(psnr_with_PSF_ver2.to('cpu').detach().numpy().copy(), 2)
  ssim_gd_list[loop] = round(ssim_with_PSF_ver2, 4)
print("Total GT Spikes")
print(spike_count_list)
if num_delta == 1:
  print("PSNR of TFW")
  psnr_tfw_list = [x.item() for x in psnr_tfw_list]
  print(psnr_tfw_list)
  print("SSIM of TFW")
  ssim_tfw_list = [x.item() for x in ssim_tfw_list]
  print(ssim_tfw_list)
  print("PSNR of TFI")
  psnr_tfi_list = [x.item() for x in psnr_tfi_list]
  print(psnr_tfi_list)
  print("SSIM of TFI")
  ssim_tfi_list = [x.item() for x in ssim_tfi_list]
  print(ssim_tfi_list)
print("PSNR of gradient descent")
psnr_gd_list = [x.item() for x in psnr_gd_list]
print(psnr_gd_list)
print("SSIM of gradient descent")
ssim_gd_list = [x.item() for x in ssim_gd_list]
print(ssim_gd_list)

"""# 可視化処理/Visualization"""

def visualize_comparison_video(video_data, video_title, path_name, output_dir, interval, iteration):
    """Creates a side-by-side video comparison."""
    fig, axs = plt.subplots(1, 1, figsize=(10, 10))

    # Helper to format titles
    def fmt(title, data):
        d = data.detach().cpu().numpy()
        return f"{title}\nmin={d.min():.2f}, max={d.max():.2f}"

    # Initial plot setup
    ims = []
    data_pairs = [
        (0, 0, video_data, video_title)
    ]

    plotted_objs = []
    for r, c, data, title in data_pairs:
        cmap = 'gray'
        vmin = 0
        vmax = 1
        im = axs.imshow(data[0].detach().cpu(), cmap=cmap, vmin=vmin, vmax=vmax)
        axs.set_title(fmt(title, data[0]))
        plt.colorbar(im, ax=axs, fraction=0.046, pad=0.04)
        plotted_objs.append(im)

    if iteration is not None:
        fig.suptitle(f"Comparison at iteration = {iteration}", fontsize=16)

    def update(frame_idx):
        for i, (r, c, data, title) in enumerate(data_pairs):
            plotted_objs[i].set_array(data[frame_idx].detach().cpu())
            axs.set_title(fmt(title, data[frame_idx]))
        return plotted_objs

    ani = animation.FuncAnimation(fig, update, frames=video_data.shape[0], interval=interval, repeat=False)
    save_path = os.path.join(output_dir, f"comp_video_{path_name}.gif")
    ani.save(save_path, writer="pillow", fps=10, dpi=300)
    plt.close(fig)
    print(f"Saved animation: {save_path}")

# 出力パスを設定
now_str = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir = os.path.join("/home/arima/work/result/hinge_ver2", datetime.now().strftime("%Y%m%d"), now_str)
os.makedirs(output_dir, exist_ok=True)

spike_gt_list = [100000, 80000, 60000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000]
visualize_comparison_video(L_gt, "Ground Truth", "L_gt", output_dir, 100, "best_mse")
for i in range(11):
  if num_delta == 1:
    visualize_comparison_video(result_tfw_list[i], f"TFW(Ns={spike_count_list[i]})", f"TFW_{spike_gt_list[i]}", output_dir, 100, "best_mse")
    visualize_comparison_video(result_tfi_list[i], f"TFI(Ns={spike_count_list[i]})", f"TFI_{spike_gt_list[i]}", output_dir, 100, "best_mse")
  visualize_comparison_video(result_gd_list[i], f"k={num_delta}, Ns={spike_count_list[i]}", f"k{num_delta}_Ns{spike_gt_list[i]}", output_dir, 100, "best_mse")
  visualize_comparison_video(spike_list[i], f"Spike GT(Ns={spike_count_list[i]})", f"spike_k{num_delta}_Ns{spike_gt_list[i]}", output_dir, 100, "best_mse")